#!/bin/bash

# see also: https://kvz.io/bash-best-practices.html
set -o errexit
set -o pipefail
set -o nounset

GRAPHIC_NAME=$1
VERSION=$2
REPO_NAME=$3
TARGET='./.build'

DEST_NAME="${GRAPHIC_NAME}"

if [ -n "${REPO_NAME}" ]; then
	DEST_NAME="${REPO_NAME}_${GRAPHIC_NAME}"
fi

if [ ! -f "$TARGET/$GRAPHIC_NAME/manifest.json" ] ; then
	echo "Error: could not find '$TARGET/$GRAPHIC_NAME/manifest.json'"
	exit 1
fi

if ! [ -x "$(command -v aws)" ] ; then
	echo "Error: you need to install the 'aws' command line tool"
	exit 1
fi

if [ -z ${S3_UPLOADS_BUCKET+x} ]; then
	# If S3_UPLOADS_BUCKET environment variable is *not* set, use the production bucket
	S3_UPLOADS_BUCKET="mrkp-wp-uploads-themarkup-org-production"
fi

# Default profile to operations_prod
if [ -z ${AWS_PROFILE+x} ]; then
	AWS_PROFILE="operations_prod"
fi

UPLOAD="s3://$S3_UPLOADS_BUCKET/graphics/$DEST_NAME/$VERSION"

if [[ `aws s3 ls "$UPLOAD"` != "" ]] ; then
	# Somehow this upload type/version already exists, something went wrong
	echo "Error: $UPLOAD already exists."
	exit 1
fi

echo "Uploading '$GRAPHIC_NAME' to $UPLOAD"
aws s3 sync "$TARGET/$GRAPHIC_NAME" "$UPLOAD"
echo "Published '$DEST_NAME' version '$VERSION'"
