#!/bin/bash

# see also: https://kvz.io/bash-best-practices.html
set -o errexit
set -o pipefail
set -o nounset

NAME=$1
VERSION=$2
TARGET='./.build'

if [ ! -f "$TARGET/$NAME/manifest.json" ] ; then
	echo "Error: could not find '$TARGET/$NAME/manifest.json'"
	exit 1
fi

if ! [ -x "$(command -v aws)" ] ; then
	echo "Error: you need to install the 'aws' command line tool"
	exit 1
fi

S3_ACL=""
if [ -z ${S3_UPLOADS_BUCKET+x} ]; then
	# If S3_UPLOADS_BUCKET environment variable is *not* set, use a testing bucket
	S3_UPLOADS_BUCKET="mrkp-wp-uploads-themarkup-org-staging"

	# For testing purposes, where there is no CDN fronting the S3 bucket
	S3_ACL="--acl public-read"
fi

UPLOAD="s3://$S3_UPLOADS_BUCKET/graphics/$NAME/$VERSION"

if [[ `aws s3 ls "$UPLOAD"` != "" ]] ; then
	# Somehow this upload type/version already exists, something went wrong
	echo "Error: $UPLOAD already exists."
	exit 1
fi

echo "Uploading '$NAME' to $UPLOAD"
aws s3 sync $S3_ACL "$TARGET/$NAME" "$UPLOAD"
echo "Published '$NAME' version '$VERSION'"
