#!/bin/bash

# see also: https://kvz.io/bash-best-practices.html
set -o errexit
set -o pipefail
set -o nounset

# if [ "$#" -lt 1 ] ; then
# 	echo "Usage: upload-graphics [target]"
# 	echo "       [target] is either a path or the name of something in wp/wp-content/graphics"
# 	exit 1
# fi

TARGET='./.build'

if [ ! -f "$TARGET/manifest.json" ] ; then
	echo "Error: could not find '$TARGET/manifest.json'"
	exit 1
fi

if ! [ -x "$(command -v aws)" ] ; then
	echo "Error: you need to install the 'aws' command line tool"
	exit 1
fi

S3_ACL=""
if [ -z ${S3_UPLOADS_BUCKET+x} ]; then

	# If S3_UPLOADS_BUCKET environment variable is *not* set, use a testing bucket
	S3_UPLOADS_BUCKET="mrkp-wp-uploads-qednews-com-production"

	# For testing purposes, where there is no CDN fronting the S3 bucket
	S3_ACL="--acl public-read"
fi

TYPE=`cat config.json | jq -r '.name'`
if ! [ -x "$(command -v jq)" ]; then
	echo "Error: You need to install the 'jq' command line tool"
	exit 1
fi

VERSION=`date +%Y%m%d%H%M%S`
UPLOAD="s3://$S3_UPLOADS_BUCKET/graphics/$TYPE/$VERSION"

if [[ `aws s3 ls "$UPLOAD"` != "" ]] ; then
	# Somehow this upload type/version already exists, something went wrong
	echo "Error: $UPLOAD already exists."
	exit 1
fi

echo "Uploading '$TYPE' to $UPLOAD"
aws s3 sync $S3_ACL "$TARGET" "$UPLOAD"
echo "Published '$TYPE' version '$VERSION'"
